/* DIALECT: POSTGRESQL */
create table news(
    id INT generated by default as identity primary key,
    title VARCHAR not null,
    url VARCHAR not null,
    date timestamp not null
);

create table images(
    id int generated by default as identity primary key,
    url varchar not null,
    news_id int references news(id)
);

create table users(
    id int generated by default as identity primary key,
    email varchar not null unique check (length(email) >= 6),
    password varchar not null check (length(password) >=5)
);

create table api_keys(
    id int generated by default as identity primary key,
    value varchar not null unique,
    created_at timestamp not null,
    user_id int references users(id) not null
);

