/* DIALECT: POSTGRESQL */
create table news(
    id INT generated by default as identity primary key,
    title VARCHAR,
    full_title varchar,
    url VARCHAR,
    date timestamp
);

create table api_keys(
    id int generated by default as identity primary key,
    value varchar,
    user_id int references users(id)
);

create table users(
    id int generated by default as identity primary key,
    email varchar,
    name varchar,
    password varchar
);